### ISSUE TITLE
Sorting feature getting disabled after first click. User should be able to sort asc and desc as user click on Sort button

### ISSUE THREAD

**Issue by nitansh11** [deepak65190/discreet-zipper-4513#25]
<img width="945" alt="image" src="https://user-images.githubusercontent.com/8274883/212898476-2f26e0e4-583d-49a2-8be5-754a127ea69c.png">

**Comment by nitansh11** [comment]
Same issue with discount

**Comment by Maalikq** [comment]
now its working
